# -*- coding: utf-8 -*-
"""BreastCancer1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16tVIfJwxngkNkjNJWoseDi4O6xCwL-mf
"""

from sklearn import datasets
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn import svm
from sklearn import metrics



bcw =datasets.load_breast_cancer()

print("Features: ", bcw.feature_names)

print("Labels: ", bcw.target_names)

X_train, X_test, y_train, y_test = train_test_split(bcw.data, bcw.target, test_size=0.3, random_state=109)

parameters = {'kernel':('linear', 'rbf'), 'C':[0.1, 1, 10], 'gamma':[0.1, 1, 10]}

clf = svm.SVC()

grid_search = GridSearchCV(clf, parameters, cv=5)
grid_search.fit(X_train, y_train)

clf = svm.SVC(**grid_search.best_params_)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy = metrics.accuracy_score(y_test, y_pred)
precision = metrics.precision_score(y_test, y_pred)
recall = metrics.recall_score(y_test, y_pred)
specificity = metrics.recall_score(y_test, y_pred, pos_label=0)

print("Best hyperparameters:", grid_search.best_params_)
print("Test set accuracy:", accuracy)
print("Test set precision:", precision)
print("Test set recall:", recall)
print("Test set specificity:", specificity)

import matplotlib.pyplot as plt
x=['Accuracy', 'Precision', 'Recall','Specificity']
y=[0.9649,
 0.9811, 
 0.9629, 
 0.9683 
]
plt.title("Result")
plt.xlabel("Result Parameters")
plt.ylabel("Percentage")
plt.bar(x,y)

import tensorflow as tf
print(tf.__version__)